// Code generated by goctl. DO NOT EDIT.
package types

type BaseMsgResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type RoomReq struct {
	RoomID string `form:"room_id"`
}

type JwtGenerateReq struct {
	RoomName string `form:"roomName"`
	Name     string `form:"name"`
	Identity string `form:"identity"`
}

type JwtInfo struct {
	AccessToken string `json:"accessToken"`
}

type JwtGenerateResp struct {
	BaseMsgResp
	Data JwtInfo `json:"data"`
}
