// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	bot "github.com/GuardedTalk/bot/internal/handler/bot"
	jwt "github.com/GuardedTalk/bot/internal/handler/jwt"
	"github.com/GuardedTalk/bot/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/join",
				Handler: bot.JoinRoomHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/leave",
				Handler: bot.LeaveRoomHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/bot"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: jwt.JwtGeneratedHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/jwt"),
	)
}
